config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#                     root GET    /                              static_pages#home
#              rails_admin        /admin                         RailsAdmin::Engine
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        registrations#cancel
#        user_registration POST   /users(.:format)               registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       registrations#new
#   edit_user_registration GET    /users/edit(.:format)          registrations#edit
#                          PATCH  /users(.:format)               registrations#update
#                          PUT    /users(.:format)               registrations#update
#                          DELETE /users(.:format)               registrations#destroy
#                 articles GET    /articles(.:format)            articles#index
#                  article GET    /articles/:id(.:format)        articles#show
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                      rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)             rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
# show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app
#

Rails.application.routes.draw do
  
  root to: "static_pages#home"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :articles , :only => [:index, :show] do
    resources :comments
  end

  resources :members , :only => [:index]

  post :find_articles, to: "static_pages#find_articles"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @articles = Article.where(:private => false).search(nil, nil).paginate(page: params[:page], per_page: 6).take(6)
    @categories = Category.all
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="objects">
  <div class="container">
    <img src="/assets/Group106.png" alt="" id="dead">
    <img src="/assets/Group106.png" alt="" id="dead2">
    <div class="contentIsland" id="chest123">
      <img src="/assets/cofre.png" alt="" id="chest1">
      <img src="/assets/cofre.png" alt="" id="chest2">
      <img src="/assets/cofre.png" alt="" id="chest3">
      <img src="/assets/cofre.png" alt="" id="chest4">
      <img src="/assets/cofre.png" alt="" id="chest5">
      <img src="/assets/cofre.png" alt="" id="chest6">
    </div>
    <div class="objects-grids search-container">
      <%= form_tag(articles_path, method: :get) do %>
        <div class="input-group">
          <span class="input-group-btn">
            <%= submit_tag '', :class => 'btn btn-default searchBtn' %>
          </span>
          <%= text_field_tag :search, params[:search], :class => 'form-control', autofocus: true %>
        </div>
      <% end %>
    </div>
  
  <div class="objects-grids">
    <% @articles.each do |article| %>
        <div class="col-md-4 objects-grid border double pd0">
          <div class="border-tl"></div>
          <div class="border-tr"></div>
          <div class="border-br"></div>
          <div class="border-bl"></div>
          <div class="cont">
            <img src="/assets/office.jpeg" alt="">
          </div>
          <div class="st"><%= article.title %></div>
          <div class="wh normalText"><%= article.description.html_safe %></div>
          <div class="borderBtn"><%= link_to "<button class='pixelBtn wh'>READ</button>".html_safe, article_path(article) %></div>
        </div>
    <%end%>
  </div>

  </div>
</div>
<div class="floorAssets">
  <img src="/assets/BAT.png" alt="" id="bat">
  <img src="/assets/BAT2.png" alt="" id="bat2">
  <img src="/assets/BAT.png" alt="" id="bat3">
  <img src="/assets/BAT2.png" alt="" id="bat4">
  <img src="/assets/hongos.png" alt="" id="hongos">
  <img src="/assets/Group11.png" alt="" id="rock">
  <img src="/assets/cofre.png" alt="" id="hongos2">
  <img src="/assets/blob.png" alt="" id="blob">
</div>