config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#                     root GET    /                              static_pages#home
#              rails_admin        /admin                         RailsAdmin::Engine
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        registrations#cancel
#        user_registration POST   /users(.:format)               registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       registrations#new
#   edit_user_registration GET    /users/edit(.:format)          registrations#edit
#                          PATCH  /users(.:format)               registrations#update
#                          PUT    /users(.:format)               registrations#update
#                          DELETE /users(.:format)               registrations#destroy
#                 articles GET    /articles(.:format)            articles#index
#                  article GET    /articles/:id(.:format)        articles#show
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                      rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)             rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
# show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app
#

Rails.application.routes.draw do
  
  root to: "static_pages#home"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :articles , :only => [:index, :show] do
    resources :comments
  end

  resources :members , :only => [:index]

  post :find_articles, to: "static_pages#find_articles"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RogueBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link href="https://fonts.googleapis.com/css?family=Coiny" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="header-nav">
        <nav class="menuCll">
          <ul class="nav">
           <li><%= link_to "Home", root_path %></li>
           <!-- <li><%= link_to "Articles", articles_path %></li> -->
           <li><%= link_to "Members", members_path %></li>
           <% if user_signed_in? %>
             <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
           <% else %>
             <li><%= link_to 'Login', new_user_session_path %></li>
           <% end%>
           </ul>
           </ul>
          <!-- <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="logo">
              <a class="navbar-brand" href="/">RogueBlog <span>It's not what you do but how you do it</span></a>
            </div>
          </div>
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
           <ul class="nav navbar-nav cl-effect-14">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Articles", articles_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to current_user.name, edit_user_registration_path %></li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end%>
            </ul>

          </div> -->
        </nav>
      </div>
    </div>
    <div class="container2">
            <div class="animate-area">
            </div>
        </div>
  </div>

  <div class="wave"></div>

  <div class="jumbotron2">
    <img src="/assets/fnd-grass.png" alt="" class="background">
    <ul class="overflow-layers">
      <li ><img src="/assets/fnd-grass.png" alt="" id="layer-1" class="layer"></li>
      <li ><img src="/assets/arboles2.png" alt="" id="layer-2" class="layer"></li>

      <li><img src="/assets/arbol.png" alt="" id="tree1"></li>
      <li><img src="/assets/arbol.png" alt="" id="tree2"></li>


      <div class="coat">
        <img src="/assets/logo-shield.png" alt="" class="shield">
        <img src="/assets/logo-sword.png" alt="" class="sword">
        <img src="/assets/logo-text.png" alt="" class="name">
      </div>
      </ul>
  </div>

  <div class="yield-content">
    <%= yield %>
  </div>

  <div class="footerBg">
    <img src="/assets/pisodungeon.png" alt="" class="pd">
  </div>
  <footer class="footer">

    <p>Copyright © 2018 RogueBlog. All rights reserved | Design by <a href="">RogueTeam</a></p>
  </footer>
</body>
</html>